name: 'release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'setup node'
      uses: actions/setup-node@v1

    - name: 'install'
      run: |
        npm i
        sudo apt-get install jq

    - name: 'release'
      run: sh ./scripts/release.sh
      env:
        OAuth: ${{ secrets.YANDEX_TRACKER_OAUTH }}
        OrgId: ${{ secrets.YANDEX_TRACKER_ORG_ID}}

    - name: 'test release'
      run: sh ./scripts/test.sh
      env:
        OAuth: ${{ secrets.YANDEX_TRACKER_OAUTH }}
        OrgId: ${{ secrets.YANDEX_TRACKER_ORG_ID}}

    - name: 'YEAH!'
      run: echo 'YEAH!'